### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by jhofstede** [kgram/equation-parser#2]
Hey! Your package looks great! I wanted to give it a try as an alternative for MathJax. However, I'm having some issues installing. Unsure if it's me. But I'm getting an error while installing this package through npm.
```
$ npm install -S equation-parser

npm ERR! path /Users/DELTA/project/node_modules/equation-parser/scripts/cli
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/DELTA/project/node_modules/equation-parser/scripts/cli'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

Is it perhaps that [this is pointing](https://github.com/kgram/equation-parser/blob/master/package.json#L27) to `./scripts/cli` while the folder is called `bin` that contains the `cli.js`?

**Comment by kgram** [comment]
That seems very likely. Funny, I only added the CLI tools for development purposes, but I haven't had any problems installing it. Then again, yarn may not perform the same checks as NPM, and I don't think I've actually used the CLI from the built package.

I'll see about getting a fix up this evening.

**Comment by kgram** [comment]
There, now it should work properly with NPM. Sorry about the mixup and the delay in fixing it. Hopefully you find it useful 🙂
